# Generated by Django 2.2.7 on 2020-02-07 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 0, 18, 3, 451411, tzinfo=utc)),
        ),
    ]
