# Generated by Django 2.2.7 on 2020-02-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_author',
        ),
    ]
