# Generated by Django 2.2.7 on 2020-02-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20200209_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tweet', to='tweets.Tweet'),
        ),
    ]
