# Generated by Django 2.2.7 on 2020-02-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_retweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retweet',
        ),
    ]
