# Generated by Django 2.2.7 on 2020-02-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200213_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='static/nopic.jpeg/', upload_to='profilepictures/'),
        ),
    ]
