# Generated by Django 2.2.7 on 2020-02-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200213_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilepicture',
            field=models.ImageField(default='nopic.jpeg', upload_to='profile_picture'),
        ),
    ]
