# Generated by Django 2.2.7 on 2020-02-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200213_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilepicture',
            field=models.FileField(default='nopic.jpeg', upload_to='profile_picture'),
        ),
    ]
